package com.shatteredpixel.shatteredpixeldungeon.test;

import com.shatteredpixel.shatteredpixeldungeon.Dungeon;
import com.shatteredpixel.shatteredpixeldungeon.actors.Actor;
import com.shatteredpixel.shatteredpixeldungeon.actors.hero.HeroClass;

import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Exercises {@link GameTestBase} itself: does @BeforeEach actually produce a usable hero+level,
 * and does state really not leak between two tests that both mutate global/static fields.
 *
 * Method order is pinned deliberately (JUnit's default order is unspecified) because
 * {@code mutateGlobalState} and {@code previousTestsMutationsDidNotLeak} only prove anything
 * if they run in that order.
 */
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class GameTestBaseSmokeTest extends GameTestBase {

	@Test
	@Order(1)
	void setUpProducesHeroAndLevel() {
		assertNotNull(Dungeon.hero, "Dungeon.hero should be initialized by @BeforeEach");
		assertTrue(Dungeon.hero.isAlive());
		assertSame(HeroClass.WARRIOR, Dungeon.hero.heroClass);

		assertNotNull(Dungeon.level, "Dungeon.level should be generated by @BeforeEach");
		assertEquals(1, Dungeon.depth);

		//hero must be registered as a processable Actor (Actor.init() was called)
		assertTrue(Actor.chars().contains(Dungeon.hero));
	}

	@Test
	@Order(2)
	void seedIsFixedAndReproducible() {
		assertEquals(42L, Dungeon.seed);
	}

	@Test
	@Order(3)
	void mutateGlobalState() {
		Dungeon.gold = 12345;
		Dungeon.depth = 7;
	}

	@Test
	@Order(4)
	void previousTestsMutationsDidNotLeak() {
		//if global state leaked from mutateGlobalState, these would fail
		assertEquals(0, Dungeon.gold);
		assertEquals(1, Dungeon.depth);
	}
}
